### ISSUE TITLE
Error when using @RouteScope in components - version 1.3.18 (and also 1.3.17)

### ISSUE THREAD

**Issue by brunovianarezende** [mvysny/karibu-testing#129]
I have a component annotated with @RouteScope and when I try to init the app in the test, I get the error:

```
Caused by: java.lang.IllegalStateException: UI bean store is not found by the initial UI id via the key 'uid-1' and it's not found by the key 'win-ROOT-2521314-0.2626611481' after relocation.
	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteStoreWrapper.relocateStore(VaadinRouteScope.java:123)
	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteStoreWrapper.lambda$getBeanStore$b500751e$1(VaadinRouteScope.java:100)
	at com.vaadin.flow.component.page.Page.retrieveExtendedClientDetails(Page.java:567)
	at com.github.mvysny.kaributesting.v10.MockPage.retrieveExtendedClientDetails(MockVaadin.kt:421)
	at com.vaadin.flow.spring.scopes.VaadinRouteScope$RouteStoreWrapper.getBeanStore(VaadinRouteScope.java:99)
	at com.vaadin.flow.spring.scopes.VaadinRouteScope.getBeanStore(VaadinRouteScope.java:412)
	at com.vaadin.flow.spring.scopes.AbstractScope.get(AbstractScope.java:44)
	at com.vaadin.flow.spring.scopes.VaadinRouteScope.get(VaadinRouteScope.java:67)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:371)
	... 103 more
```
it seems to me this error is caused by this commit: https://github.com/mvysny/karibu-testing/commit/7d0435e03717aadf6d4e5bb8c9f26314a409ebca. I tested using version 1.3.16 and it works ok.

This is the code in my test class:

```
  private static final Routes routes = new Routes().autoDiscoverViews("the.package");

  @Autowired
  private ApplicationContext ctx;

  @BeforeEach
  public void mockVaadin() {
    final Function0<UI> uiFactory = UI::new;
    final SpringServlet servlet = new MockSpringServlet(routes, ctx, uiFactory);
    MockVaadin.setup(uiFactory, servlet);
  }

  @BeforeEach
  public void navigate() {
    UI.getCurrent()
        .navigate(AView.class);
    _assertOne(AView.class);
  }
```

and this is what I have in my POM:

```
    <dependency>
        <groupId>com.github.mvysny.kaributesting</groupId>
        <artifactId>karibu-testing-v10-spring</artifactId>
        <version>1.3.18</version>
        <scope>test</scope>
    </dependency>
```

The code that triggers the bug is something like:

```
@Route(...)
public class ARoute {
...
  @Inject
private TheClassThatCausesProblem the classe;
...
}
```
and:
```
@RouteScope
public class TheClassThatCausesProblem extends HorizontalLayout {
...
}
```

```

**Comment by mvysny** [comment]
Thank you for letting me know :+1: I'll try to add this test to Karibu itself, hopefully I'll be able to reproduce it on my machine. At first look it looks to me that it's not possible for 7d0435e03717aadf6d4e5bb8c9f26314a409ebca to cause this; however it's good to know that 1.3.16 worked okay. @brunovianarezende could you please check 1.3.17 whether it's also affected?

**Comment by mvysny** [comment]
Also, which version of vaadin-spring.jar are you using please, and which Vaadin version?

**Comment by brunovianarezende** [comment]
> Thank you for letting me know +1 I'll try to add this test to Karibu itself, hopefully I'll be able to reproduce it on my machine. It's good to know that 1.3.16 worked okay. @brunovianarezende could you please check 1.3.17 whether it's also affected?

Yes, 1.3.17 is affected too.

**Comment by brunovianarezende** [comment]
> Also, which version of vaadin-spring.jar are you using please, and which Vaadin version?

We use: 
```
    <dependency>
      <groupId>com.vaadin</groupId>
      <artifactId>
        vaadin-spring-boot-starter
      </artifactId>
      <version>${vaadin.version}</version>
    </dependency>
```
where `${vaadin.version}` is equal to 23.1.1, i.e. vaadin-spring is 23.1.1 and vaadin is 23.1.1.

**Comment by mvysny** [comment]
Sorry - I tried to upgrade Spring in Karibu-Testing in hopes to create a reproducible test, but Spring failed with random class incompatibility exceptions. However, let me try to figure out a blind workaround.

**Comment by mvysny** [comment]
The new implementation of `retrieveExtendedClientDetails()` seems to interfere with Spring. It was introduced during the fix of #118 . I'll add a flag to turn this functionality off as a workaround.

**Comment by mvysny** [comment]
The flag is called `fakeExtendedClientDetails` and it can be turned off starting with Karibu 1.3.20. Please see the documentation for more details.

**Comment by mvysny** [comment]
Should be fixed in Karibu-Testing 2.2.3. Closing; please feel free to reopen if the bug persists.
