### ISSUE TITLE
Update Vaadin 24.1.9 breaks Karibu on MockRouteNotFoundError

### ISSUE THREAD

**Issue by timomeinen** [mvysny/karibu-testing#158]
The latest change in Vaadin 24.1.9 introduced an addtional check in [this commit](https://github.com/vaadin/flow/commit/15e05fd):

com.vaadin.flow.router.internal.AbstractNavigationStateRenderer#handleTriggeredBeforeEvent

        if (beforeEvent.hasRerouteTarget()
                && (!isSameNavigationState(beforeEvent.getRerouteTargetType(),
                        beforeEvent.getRerouteTargetRouteParameters())
                        || !navigationState.getResolvedPath()
                                .equals(beforeEvent.getRerouteUrl()))) {
            return Optional.of(reroute(event, beforeEvent));
        }

When called with an instance of MockRouteNotFoundError the `navigationState.getResolvedPath()` is null and we get a NPE:

```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "com.vaadin.flow.router.NavigationState.getResolvedPath()" is null
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handleTriggeredBeforeEvent(AbstractNavigationStateRenderer.java:672) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEvent(AbstractNavigationStateRenderer.java:602) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEvent(AbstractNavigationStateRenderer.java:577) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:453) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:210) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.ErrorStateRenderer.handle(ErrorStateRenderer.java:106) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.reroute(AbstractNavigationStateRenderer.java:715) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handleTriggeredBeforeEvent(AbstractNavigationStateRenderer.java:673) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handleTriggeredBeforeEvent(JavaScriptNavigationStateRenderer.java:99) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEvent(AbstractNavigationStateRenderer.java:602) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.sendBeforeEnterEvent(AbstractNavigationStateRenderer.java:577) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.createChainIfEmptyAndExecuteBeforeEnterNavigation(AbstractNavigationStateRenderer.java:453) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.router.internal.AbstractNavigationStateRenderer.handle(AbstractNavigationStateRenderer.java:210) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.component.internal.JavaScriptNavigationStateRenderer.handle(JavaScriptNavigationStateRenderer.java:78) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.component.UI.handleNavigation(UI.java:1857) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.component.UI.navigate(UI.java:1246) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.component.UI.navigate(UI.java:1201) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.component.UI.navigate(UI.java:1004) ~[flow-server-24.1.11.jar:24.1.11]
	at com.vaadin.flow.component.UI.navigate(UI.java:897) ~[flow-server-24.1.11.jar:24.1.11]
```

My test expects a com.vaadin.flow.router.NotFoundException in order to check if the access was correctly prohibited. I tried to workaround, but I do not fully understand the concept of the MockRouteNotFoundError vs. NotFoundException.

When I remove the MockRouteNotFoundError from the routes the NPE does not appear, but the test does not work neither.

Any advice? Thanks.

**Comment by timomeinen** [comment]
You can see the same problem in the [example project](https://github.com/mvysny/vaadin-spring-karibu-testing) if updating to 24.1.9 in this test:

https://github.com/mvysny/vaadin-spring-karibu-testing

com.example.application.views.about.AboutViewTest#userCantSeeThis

**Comment by mvysny** [comment]
Yup, thank you for letting me know. This looks like a bug in Vaadin, I’ve filed https://github.com/vaadin/flow/issues/17597 . Looks like the best approach is to wait for next Vaadin to be released.

**Comment by mvysny** [comment]
On "MockRouteNotFoundError vs. NotFoundException":

The NotFoundException is just a page which is shown when the browser navigates to a non-existing route. That's usually what we want, but for tests it's better to throw an exception eagerly instead. That's what MockRouteNotFoundError does - when Vaadin cannot find the target route and tries to open MockRouteNotFoundError, the MockRouteNotFoundError class throws an exception in its constructor, which then bubbles out and makes the test fail.

**Comment by timomeinen** [comment]
Thanks for the explanation. That is exactly what I want to achieve in my tests. Got it.

**Comment by timomeinen** [comment]
@mvysny Thank you. Tested and works as expected. That was a quickfix...
