### ISSUE TITLE
A page with CheckboxGroup causes exception during pretty print

### ISSUE THREAD

**Issue by satorstefan** [mvysny/karibu-testing#169]
Hello Martin,

I accidentally searched for a button on a page where this button is not visible. This page also contains a checkbox group.

I got the following exception, which is probably not what you intended:

java.lang.IllegalAccessError: class com.github.mvysny.kaributesting.v10.GridKt tried to access private method 'com.vaadin.flow.data.provider.DataProvider com.vaadin.flow.component.checkbox.CheckboxGroup.getDataProvider()' (com.github.mvysny.kaributesting.v10.GridKt and com.vaadin.flow.component.checkbox.CheckboxGroup are in unnamed module of loader 'app')

	at com.github.mvysny.kaributesting.v10.GridKt.getDataProvider(Grid.kt:937)
	at com.github.mvysny.kaributesting.v10.PrettyPrintTreeKt.toPrettyString(PrettyPrintTree.kt:137)
	at com.github.mvysny.kaributesting.v10.PrettyPrintTree$Companion.ofVaadin(PrettyPrintTree.kt:55)
	at com.github.mvysny.kaributesting.v10.PrettyPrintTree$Companion.ofVaadin(PrettyPrintTree.kt:57)
	at com.github.mvysny.kaributesting.v10.PrettyPrintTree$Companion.ofVaadin(PrettyPrintTree.kt:57)
	at com.github.mvysny.kaributesting.v10.PrettyPrintTree$Companion.ofVaadin(PrettyPrintTree.kt:57)
	at com.github.mvysny.kaributesting.v10.PrettyPrintTree$Companion.ofVaadin(PrettyPrintTree.kt:57)
	at com.github.mvysny.kaributesting.v10.PrettyPrintTree$Companion.ofVaadin(PrettyPrintTree.kt:57)
	at com.github.mvysny.kaributesting.v10.PrettyPrintTreeKt.toPrettyTree(PrettyPrintTree.kt:64)
	at com.github.mvysny.kaributesting.v10.LocatorKt._find(Locator.kt:195)
	at com.github.mvysny.kaributesting.v10.LocatorKt._get(Locator.kt:155)
	at com.github.mvysny.kaributesting.v10.LocatorJ._get(LocatorJ.java:65)
	at de.hahn.pageobjects.SafeguardEditorPage.getSaveButton(SafeguardEditorPage.java:187)
	at de.hahn.pageobjects.SafeguardEditorPage.saveIsEnabled(SafeguardEditorPage.java:229)
	at de.hahn.safeguard.SafeguardPoolEditorTest.creating_a_safeguard_enables_all_buttons(SafeguardPoolEditorTest.java:64)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

**Comment by satorstefan** [comment]
This line causes the problem:
![image](https://github.com/mvysny/karibu-testing/assets/25597168/1044fc9a-497d-443d-889f-6d5598bd4ce1)

**Comment by mvysny** [comment]
Which Karibu Testing and which Vaadin version please?

**Comment by satorstefan** [comment]
<vaadin.version>24.1.4</vaadin.version>
<karibu.version>2.1.4</karibu.version>

**Comment by satorstefan** [comment]
![image](https://github.com/mvysny/karibu-testing/assets/25597168/d35d2696-94d2-4157-94dc-171ab5a834ae)

**Comment by mvysny** [comment]
Please upgrade to newest Vaadin 24.4, the `CheckboxGroup.getDataProvider()` function is public there.

**Comment by satorstefan** [comment]
Hello Martin,
I dont think this works:
![image](https://github.com/user-attachments/assets/a5444683-25e7-4b5c-9527-3db45e106e14)

The checkbox does not get selected.

       <vaadin.version>24.4.7</vaadin.version>
        <karibu.version>2.1.5</karibu.version>

**Comment by satorstefan** [comment]
Also in the documentation the java version of this call is not mentioned:

Call checkboxGroup.selectByLabel("Item #1", "Item #3") to select items with given labels (since KT 1.3.15).

**Comment by mvysny** [comment]
Please create a new issue.
