### ISSUE TITLE
Logout doesn't work anymore with 2.1.5

### ISSUE THREAD

**Issue by simasch** [mvysny/karibu-testing#174]
After upgrading to 2.1.5 logout is broken:

```
java.lang.UnsupportedOperationException: not implemented

	at com.github.mvysny.fakeservlet.FakeResponse.isCommitted(FakeResponse.kt:113)
	at jakarta.servlet.ServletResponseWrapper.isCommitted(ServletResponseWrapper.java:176)
	at org.springframework.security.web.authentication.AbstractAuthenticationTargetUrlRequestHandler.handle(AbstractAuthenticationTargetUrlRequestHandler.java:87)
	at org.springframework.security.web.authentication.logout.SimpleUrlLogoutSuccessHandler.onLogoutSuccess(SimpleUrlLogoutSuccessHandler.java:41)
	at com.vaadin.flow.spring.security.AuthenticationContext.lambda$logout$7e8b7cde$1(AuthenticationContext.java:133)
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:489)
	at com.vaadin.flow.component.UI.accessSynchronously(UI.java:450)
	at com.vaadin.flow.spring.security.AuthenticationContext.logout(AuthenticationContext.java:131)
	at ch.jtaf.configuration.security.SecurityContext.logout(SecurityContext.java:61)
	at ch.jtaf.ui.layout.MainLayout.lambda$createHeaderContent$b71f5360$2(MainLayout.java:90)
```

**Comment by mvysny** [comment]
The surrounding Spring code is:
```java
	protected void handle(HttpServletRequest request, HttpServletResponse response, Authentication authentication)
			throws IOException, ServletException {
		String targetUrl = determineTargetUrl(request, response, authentication);
		if (response.isCommitted()) {
			this.logger.debug(LogMessage.format("Did not redirect to %s since response already committed.", targetUrl));
			return;
		}
		this.redirectStrategy.sendRedirect(request, response, targetUrl);
	}
```
I guess we can pretend that the response is always open and never committed (the http response code is never written). I'll make the `isCommitted()` function return false by default.

**Comment by simasch** [comment]
Thank you @mvysny
