### ISSUE TITLE
Instantiating PolymerTemplate+npm fails

### ISSUE THREAD

**Issue by mvysny** [mvysny/karibu-testing#26]
```
Caused by: java.lang.NullPointerException
	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsFromWebpack(FrontendUtils.java:402)
	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsContent(FrontendUtils.java:367)
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getSourcesFromStats(NpmTemplateParser.java:172)
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:105)
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200)
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88)
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103)
	at org.test.MyComponent.<init>(MyComponent.java:32)
	at org.test.MainView.<init>(MainView.java:18)
```

**Comment by mvysny** [comment]
Reproduced in a simple project.

**Comment by mvysny** [comment]
Flow needs to load the sources for `@JsModule` and the current implementation reads that from a file named `stats.json` produced by webpack. We need to mock the `stats.json` file.

**Comment by mvysny** [comment]
Fixed in 781c4f55bc751efbc461258f44116ac59900de9e - now Karibu-Testing should auto-detect NPM mode and should auto-scan the `frontend/` folder and register all js files found there, so that they can be loaded via `NpmTemplateParser` in `PolymerTemplate`

**Comment by mvysny** [comment]
I've changed the implementation and hacked around NpmTemplateParser in an ugly way (re-setting NpmTemplateParser.INSTANCE). This way we have more options to load the templates also from META-INF/resources, and by custom loaders at `NpmTemplateParser.customLoaders`.

However, it would be great to have a less hacky way: https://github.com/vaadin/flow/issues/6537

**Comment by mvysny** [comment]
Because of crazy mock reflection calls this gets logged in Java 11:
```
WARNING: An illegal reflective access operation has occurred

WARNING: Illegal reflective access by com.github.mvysny.kaributesting.v10.UtilsKt (file:/home/travis/build/mvysny/karibu-testing/karibu-testing-v10/build/libs/karibu-testing-v10-1.1.12-SNAPSHOT.jar) to field java.lang.reflect.Field.modifiers

WARNING: Please consider reporting this to the maintainers of com.github.mvysny.kaributesting.v10.UtilsKt

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: All illegal access operations will be denied in a future release
```
Not good. Hopefully Core Vaadin guys will allow to provide my own implementations of `NpmTemplateParser`.

**Comment by HaydenDekker** [comment]
Ahh great! Saved the day. Just to note, for anyone in the future, I was using a eclipse workspace addon where you need to put the frontend folder in the resources/META-INF/resources/frontend so I was getting the error about polymer not being found. I simple copied the polymer .js into the local projects /frontend and Karibu picked it up.

**Comment by mvysny** [comment]
In order to use Karibu-Testing on JDK 11 and higher, please use Karibu-Testing 1.2.3 or higher - the reflection call is replaced by a factory call :+1: 

@HaydenDekker Karibu-Testing should also support addon development and should pick up frontend resources from `src/main/resources/META-INF/resources/frontend` as well. If not, it's a bug. Could you please open a new bug report and attach the code/project there, so that I can investigate?
