### ISSUE TITLE
ConfirmDialog multiple times present in MockedUI

### ISSUE THREAD

**Issue by knoobie** [mvysny/karibu-testing#34]
Simplified example:

I have a form within my view that implements a BeforeLeaveObserver:

```java
public class QuestionForm extends FormLayout implements BeforeLeaveObserver {

  @Override
  public void beforeLeave(BeforeLeaveEvent event) {
      // postpone the view change
      ContinueNavigationAction postponedNavigationAction = event.postpone();
      ConfirmDialog dialog = new ConfirmDialog("Unsaved changed", "You sure?", "Leave Page", e -> postponedNavigationAction.proceed(), "Stay", e -> {});
      dialog.open();
  }
}
```

In my test I try to verify that the BeforeLeaveObserver is triggered and can be retrigged a second time if the user presses once "Stay" and the second time "Leave Page" -> resulting in a view change.

```java
    UI.getCurrent().navigate(QuestionView.class);

    // Open other view to trigger confirm dialog
    UI.getCurrent().navigate(QuestionsView.class);
    // press "cancel" 
    ConfirmDialogKt._fireCancel(_get(ConfirmDialog.class)); // stay on the view

    // Try to navigate again
    UI.getCurrent().navigate(QuestionsView.class);
    // press confirm
    ConfirmDialogKt._fireConfirm(_get(ConfirmDialog.class)); // move to another view

    // ... assert view changed
```

Currently my test fails at line: `ConfirmDialogKt._fireConfirm(_get(ConfirmDialog.class))` with: "Too many visible ConfirmDialogs (2) in MockedUI[] matching ConfirmDialog: [ConfirmDialog[], ConfirmDialog[]].

P.S. If I remember correctly, I had an error like this with Notifications as well, I removed that test - so no change to verify it.

Versions:
- Vaadin: 14.1.28
- karibu-testing-v10: 1.1.23

**Comment by mvysny** [comment]
Hi, thank you for letting me know :+1: 

I've written a test suite trying to replicate the issue you're having, but it works for me. Please find the test suite here: https://github.com/mvysny/karibu-testing/blob/1.1.x/karibu-testing-v10/kt10-tests/src/main/kotlin/com/github/mvysny/kaributesting/v10/NavigatorTest.kt

Maybe there is some glaring omission from my part... :) Alternatively it could be that I'm using Vaadin 14.2.0, and the navigation logic changed a bit since Vaadin 14.1.28. Maybe could you try and upgrade Vaadin temporarily, to see whether the situation improves?

Also I remember that there is a special code for dialog cleanup: `TestingLifecycleHookKt.cleanupDialogs()`. It's being called periodically from `TestingLifecycleHookKt.testingLifecycleHook` variable. Have you perhaps overridden that functionality?

Also, are you closing the dialog when "Yes" is pressed? The dialogs won't disappear automatically when navigation is performed.

**Comment by knoobie** [comment]
@mvysny thanks for looking into this and thanks for the link to `TestingLifecycleHookKt.cleanupDialogs()`- I think there is the issue :) 

I'm using `com.vaadin.flow.component.confirmdialog.ConfirmDialog` (which doesn't extend Dialog) 

https://github.com/mvysny/karibu-testing/blob/bef012dd7b840a91a2293e906df0f40a8b52eafb/karibu-testing-v10/src/main/kotlin/com/github/mvysny/kaributesting/v10/TestingLifecycleHook.kt#L62-L65

Could that explain the difference? :)

**Comment by mvysny** [comment]
Gotcha, good find! That's actually the problem here: the `ConfirmDialogKt._fireConfirm()` call wouldn't close the confirm dialog and the `fun cleanupDialogs()` wouldn't clean up `ConfirmDialog`s since they do not extend `Dialog`.

I've fixed Karibu-Testing to also close & cleanup ConfirmDialogs. Could you please try it out? You can simply pull newest code from 1.1.x branch, run `./gradlew clean build publishToMavenLocal` then use version 1.1.25-SNAPSHOT.

ConfirmDialog cleanup implemented in a74e66e31c4fdd70a0d7e1edde02eda9fa22ac4f

**Comment by knoobie** [comment]
It's working with 1.1.25-SNAPSHOT :) 

![image](https://user-images.githubusercontent.com/3968629/82672777-18bbf580-9c41-11ea-9595-04bd5d6c0037.png)

FYI: execution of gradle with tests resulted in the following log. I disabled tests with -x to create the snapshot.

```log
> Task :karibu-testing-v10:kt10-testrun-vaadin13:test

AllTests > binder test > verbose message FAILED
    java.lang.AssertionError: Expected <Validation has failed for some fields: field validation errors: [blank: ERROR must not be null, value=''], bean validation errors: []>, actual <Validation has failed for some fields: field validation errors: [blank: ERROR darf nicht null sein, value=''], bean validation errors: []>.
        at kotlin.test.DefaultAsserter.fail(DefaultAsserter.kt:16)
        at kotlin.test.Asserter$DefaultImpls.assertTrue(Assertions.kt:196)
        at kotlin.test.DefaultAsserter.assertTrue(DefaultAsserter.kt:11)
        at kotlin.test.Asserter$DefaultImpls.assertEquals(Assertions.kt:215)
        at kotlin.test.DefaultAsserter.assertEquals(DefaultAsserter.kt:11)
        at kotlin.test.AssertionsKt__AssertionsKt.assertEquals(Assertions.kt:51)
        at kotlin.test.AssertionsKt.assertEquals(Unknown Source)
        at kotlin.test.AssertionsKt__AssertionsKt.assertEquals$default(Assertions.kt:50)
        at kotlin.test.AssertionsKt.assertEquals$default(Unknown Source)
        at kotlin.test.AssertionsKt__AssertionsKt.expect(Assertions.kt:97)
        at kotlin.test.AssertionsKt.expect(Unknown Source)
        at com.github.mvysny.kaributesting.v10.BinderUtilsTestKt$binderTestbatch$1.invoke(BinderUtilsTest.kt:27)
        at com.github.mvysny.kaributesting.v10.BinderUtilsTestKt$binderTestbatch$1.invoke(BinderUtilsTest.kt)
        at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$1$1.invoke(DynaTestEngine.kt:91)
        at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$1$1.invoke(DynaTestEngine.kt:27)
        at com.github.mvysny.dynatest.engine.DynaNodeTestDescriptor.runBlock(DynaTestEngine.kt:199)
        at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$1.invoke(DynaTestEngine.kt:91)
        at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$2.invoke(DynaTestEngine.kt:119)
        at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$2.invoke(DynaTestEngine.kt:115)
        at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$2.invoke(DynaTestEngine.kt:115)
        at com.github.mvysny.dynatest.engine.DynaTestEngine$execute$2.invoke(DynaTestEngine.kt:115)
        at com.github.mvysny.dynatest.engine.DynaTestEngine.execute(DynaTestEngine.kt:130)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
        at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at com.sun.proxy.$Proxy2.stop(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:132)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:412)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
        at java.lang.Thread.run(Thread.java:748)

237 tests completed, 1 failed

> Task :karibu-testing-v10:kt10-testrun-vaadin13:test FAILED

```

**Comment by mvysny** [comment]
Excellent, thank you for confirming :) Closing as fixed.

The issue with the test is probably that it only works with the English locale. I've pushed a change which enforces english locale throughout the tests. Could you please try running those tests again?

**Comment by knoobie** [comment]
Tests working for me now as well - thanks!
