### ISSUE TITLE
Vaadin 14 + Springboot + Vaadin Card - Instantiating PolymerTemplate+npm fails

### ISSUE THREAD

**Issue by xeonn** [mvysny/karibu-testing#48]
Hi guys,

I am using Vaadin component Card (https://vaadin.com/directory/component/card) and encounter the same issue mentioned in #26 .

I am using Vaadin springboot starter 14.3.2

Without the card, the testing works perfect. Am I missing out something?

Any advice will be appreciated.

Stacktrace
`Caused by: java.lang.NullPointerException: null
	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsFromWebpack(FrontendUtils.java:430) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsContent(FrontendUtils.java:379) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getSourcesFromStats(NpmTemplateParser.java:189) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:110) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103) ~[flow-server-2.3.2.jar:2.3.2]
	at com.github.appreciated.card.AbstractCard.<init>(AbstractCard.java:22) ~[card-2.0.0.beta4.jar:2.0.0.beta4]
	at com.github.appreciated.card.Card.<init>(Card.java:19) ~[card-2.0.0.beta4.jar:2.0.0.beta4]`

**Comment by mvysny** [comment]
Hi, which version of Karibu-Testing are you using please? The problem might be that the Card component transitively pulls in webjars, which may confuse Karibu-Testing to think that it is in fact running in compatibility mode.

Please try out with the newest 1.2.5 - it only supports npm mode and will complain loudly if there's any webjar on classpath.

**Comment by xeonn** [comment]
I am using Karibu-Testing 1.2.4.

Sorry for the trouble. If its not an important component as mentioned in https://vaadin.com/docs/flow/migration/5-components.html (replacement for Panel), i wouldn't have bothered you.

I will let you know the outcome of 1.2.5 in a short while.

**Comment by xeonn** [comment]
This is the outcome of 1.2.5

```
Caused by: java.lang.NullPointerException: null
	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsFromWebpack(FrontendUtils.java:430) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.server.frontend.FrontendUtils.getStatsContent(FrontendUtils.java:379) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getSourcesFromStats(NpmTemplateParser.java:189) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.NpmTemplateParser.getTemplateContent(NpmTemplateParser.java:110) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.TemplateDataAnalyzer.parseTemplate(TemplateDataAnalyzer.java:200) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.TemplateInitializer.<init>(TemplateInitializer.java:91) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:88) ~[flow-server-2.3.2.jar:2.3.2]
	at com.vaadin.flow.component.polymertemplate.PolymerTemplate.<init>(PolymerTemplate.java:103) ~[flow-server-2.3.2.jar:2.3.2]
	at com.github.appreciated.card.AbstractCard.<init>(AbstractCard.java:22) ~[card-2.0.0.beta4.jar:2.0.0.beta4]
	at com.github.appreciated.card.Card.<init>(Card.java:19) ~[card-2.0.0.beta4.jar:2.0.0.beta4]
	at my.com.lrsb.ibcims.ui.view.kyc.KycPersonalForm.createPersonalInformation(KycPersonalForm.java:219) ~[classes/:na]
	at my.com.lrsb.ibcims.ui.view.kyc.KycPersonalForm.createForm(KycPersonalForm.java:200) ~[classes/:na]
	at my.com.lrsb.ibcims.ui.view.kyc.KycPersonalForm.<init>(KycPersonalForm.java:108) ~[classes/:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_231]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_231]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_231]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_231]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	... 86 common frames omitted
```

**Comment by mvysny** [comment]
No problem :) 

From the stack trace I can see that Karibu-Testing mocking is not activated properly for some reason. If it was activated properly, the `MockNpmTemplateParser.getSourcesFromTemplate()` would have been called, which never returns null, and therefore `NpmTemplateParser.java:110` can never be reached.

You can verify this by placing a breakpoint into `PolymerTemplate:103` and checking out the value of:

* `VaadinService.getCurrent().getInstantiator().getTemplateParser()`: it should return `MockNpmTemplateParser` instance, but in your case it's probably returning `NpmTemplateParser`.
* `VaadinService.getCurrent().getInstantiator()` should return `MockInstantiator` instead of `DefaultInstantiator` or `SpringInstantiator`.

Are you perhaps using Spring? If yes, then you will need to revisit the Karibu-Testing-related mocking code: in the `MockService` you need to override also the `getInstantiator()` method. However, actually Karibu-Testing now provides those mocking classes for Spring out-of-the-box; please see the https://github.com/mvysny/t-shirt-shop-example example project on how to setup Karibu-Testing properly with Spring.

**Comment by xeonn** [comment]
Thanks for your prompt response.

Yes, I am using Springboot 2.3.3 with Vaadin Springboot Starter 14.3.2.

I will try as per your suggestion. Its gonna take awhile coz I need to activate my IDE debugging feature.

**Comment by mvysny** [comment]
@xeonn have the suggestion worked for you please?

**Comment by mvysny** [comment]
Closing as inactive
