### ISSUE TITLE
NoSuchMethodError with Vaadin 20

### ISSUE THREAD

**Issue by mvysny** [mvysny/karibu-testing#66]
Using Karibu-Testing with Vaadin 20.0.0.alpha3 fails with

```
java.lang.NoSuchMethodError: 'com.vaadin.flow.server.VaadinServletService com.vaadin.flow.server.VaadinServlet.getService()'

	at com.github.mvysny.kaributesting.v10.MockVaadin.setup(MockVaadin.kt:85)
	at com.github.mvysny.kaributesting.v10.MockVaadin.setup(MockVaadin.kt:55)
	at com.github.mvysny.kaributesting.v10.MockVaadin.setup$default(MockVaadin.kt:52)
```

When that's worked around via reflection, the code fails elsewhere at

```
java.lang.NoSuchMethodError: 'void com.vaadin.flow.server.VaadinServletRequest.<init>(javax.servlet.http.HttpServletRequest, com.vaadin.flow.server.VaadinServletService)'

	at com.github.mvysny.kaributesting.v10.MockVaadin.createSession(MockVaadin.kt:170)
	at com.github.mvysny.kaributesting.v10.MockVaadin.setup(MockVaadin.kt:92)
```
This can also be fixed via reflection, but it's getting too crazy to maintain. There has been also countless nasty class definition hacks because of Vaadin 19.

I think it's time to drop compatibility for Vaadin 19- in Karibu-Testing master, while creating branch for Vaadin 14.x.y. Not happy with this since any fixes for 14.x.y will have to be merged into master, possibly causing nasty merge conflicts, but there's no other way.

Unfortunately the Vaadin 22 LTS is far away, so we will have to live with the merges for some time.

**Comment by mvysny** [comment]
I was somehow able to reflection my way into support of Vaadin 20..... Let's keep it like this for now. But if more things break, I'll definitely fork a branch and cleanup master from all of that crazy reflection stuff.
